name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python 04-prompt-engineering-fundamentals/1-introduction.ipynb
