name: CI

on:
  push:
    branches:
      - main

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Convert Jupyter Notebook to script
        run: jupyter nbconvert --to script 04-prompt-engineering-fundamentals/1-introduction.ipynb

      - name: List files in the directory
        run: ls 04-prompt-engineering-fundamentals

      - name: Run tests
        run: python 04-prompt-engineering-fundamentals/1-introduction.py
